name: Variables Playground Workflow
on:
  workflow_dispatch:
    inputs:
      value:
        description: 'Some input value'
        default: 'default_input'
        required: true

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      DAY_OF_WEEK: Friday
    steps:
      - name: Echo input
        run: echo "${{ github.event.inputs.value }}"
      - name: Print environment variables
        run: echo "Hello my name is $FIRST_NAME and today is ${{env.DAY_OF_WEEK}}"
        env:
          FIRST_NAME: Tejas

